### ISSUE TITLE
A Combined Repair Crew Dispatch Problem for Resilient Electric and Natural Gas System Considering Reconfiguration and DG Islanding

### ISSUE THREAD

**Issue by mohsentava** [TesLarry/open-scientific-data#1]

**Comment by TesLarry** [comment]
Hi, could you please provide more description about your issues in terms of this article?

**Comment by TesLarry** [comment]
Hi, I am willing to known the details of your issues. Please leave a comment here. However, if no further information is provided in the next 24 hours, this issue will be closed.
